baseURL: "https://hattomo.github.io/"
title: Hattomo
paginate: 5
theme: PaperMod

enableGitInfo: false # git modified date
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
HasCJKLanguage: true

#googleAnalytics: UA-187976627-1
GoogleAnalytics: G-352SDD97BP # GA4

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Hattomo
    description: "Hattomo description"
    author: [""]
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"] google crawler

    defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowWordCount: true
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: true
    tocopen: true
    math: false
    ShowBreadCrumbs: true

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true

        favicon: "images/favicon/favicon.ico"
        favicon16x16: "images/favicon/favicon-16x16.png"
        favicon32x32: "images/favicon/favicon-32x32.png"
        apple_touch_icon: "images/favicon/apple-icon-180x180.png"
        # safari_pinned_tab: "<link / abs url>"

    label:
        text: "Hattomo"
        icon: false
        iconHeight: 30

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        # imageUrl: "<img location>" google crawler
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hello World"
        Content: Welcome to Hattomo blog

    socialIcons:
        - name: github
          url: "https://github.com/Hattomo"
        # - name: twitter
        #  url: "https://twitter.com/Hattomo_"
        - name: rss
          url: https://Hattomo.github.io/index.xml

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: search 
          name: Search 🔎
          url: /search/
          weight: 10
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 30
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 40
        - identifier: about
          name: About
          url: /about
          weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
    highlight:
        anchorLineNos: false
        codeFences: true
        guessSyntax: true
        lineNos: false
        noClasses: false
        pygmentsUseClasses: true
        pygmentsCodefences: true
        style: monokailight
    goldmark:
        renderer:
            unsafe: true