name: Build GH-Pages

on:
  schedule:
    - cron:  '0 15 * * *'
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          # fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --gc --verbose --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: Hattomo/Hattomo.github.io
          publish_branch: main
          publish_dir: ./public
